services:
  - type: web
    name: legal-assistant-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        fromService:
          type: web
          name: legal-assistant-api
          property: port
    disk:
      name: chroma-db
      mountPath: /opt/render/project/src/chroma_db
      sizeGB: 1
